trigger:
- main  # Adjust the trigger as needed (e.g., master, develop)

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      name: 'linux-pool'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: 'laaouidisoufiane/nginx'
        dockerfile: '**/Dockerfile'
        containerRegistry: 'dockerhub-cred'
        tags: |
          v1.$(Build.BuildId)  # Dynamic tag using build ID

    - script: |
        echo "Cleaning up the locally generated Docker image..."
        docker rmi laaouidisoufiane/nginx:v1.0-$(Build.BuildId) || true
      displayName: 'Cleanup locally generated Docker image'
