trigger:
- main  # Adjust the trigger as needed (e.g., master, develop)

variables:
  tag: '$(Build.BuildId)'
  imageName: 'laaouidisoufiane/nginx'  # Replace with your image name
  image_tag: '$(imageName):v1.0-$(tag)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build job
    pool:
      name: 'linux-pool'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'dockerhub-cred'
        tags: |
          $(tag)

    - script: |
        echo "Cleaning up the locally generated Docker image..."
        docker rmi $(image_tag) || true
      displayName: 'Cleanup locally generated Docker image'

    - script: |
        echo "Substituting image tag in deployment YAML..."
        sed -i "s|{{IMAGE_TAG}}|$image_tag|g" $(Build.SourcesDirectory)/kube/deploy-nginx.yaml
      displayName: 'Update image in deploy-nginx.yaml'

    - task: AzureCLI@2
      displayName: 'Deploy to AKS'
      inputs:
        azureSubscription: 'arm-conn'  # Replace with your Azure subscription
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo "Logging in to Azure..."
          az aks get-credentials --resource-group rg1 --name Aks1
          kubectl apply -f $(Build.SourcesDirectory)/kube/deploy-nginx.yaml

