trigger:
  branches:
    include:
      - main  # Change this to the branch you want to trigger on

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate image for Docker build

steps:
- task: Checkout@1  # Checkout code from the repository
  displayName: 'Checkout code'

- task: Docker@2  # Use Docker task to login to Docker Hub
  inputs:
    containerRegistry: 'dockerhub-cred'  # Define Docker Hub connection (service connection) in Azure DevOps
    command: 'login'
  displayName: 'Log in to Docker Hub'

- task: Docker@2  # Build the Docker image
  inputs:
    containerRegistry: 'dockerhub-cred'
    repository: 'laaouidisoufiane/nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)  # Use Azure DevOps build number as the tag
      latest
  displayName: 'Build and Push Docker image'


